openapi: 3.0.1
info:
  title: Chotuve app server
  description: The app server of Chotuve
  version: 1.0.0
servers:
- url: /
tags:
- name: user
  description: Operations with user
- name: video
  description: Operations with user's videos
- name: friendship
  description: Operations over user's friendships
paths:
  /user:
    get:
      tags:
      - user
      summary: Query users
      description: Queries all the user information
      parameters:
      - name: email
        in: query
        description: The user name for login
        required: true
        schema:
          type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Missing email
          content: {}
        404:
          description: User not found
          content: {}
    put:
      tags:
      - user
      summary: Update users profile
      description: Updates the data of the user
      requestBody:
        description: The user data to be updated
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
        - bearerAuth: []
      responses:
        200:
          description: Successful operation
          content: {}
        400:
          description: Invalid or missing fields or the message is not a json
          content: {}
        401:
          description: Access token is missing or invalid
          content: {}
        403:
          description: Not authorized
          content: {}
      x-codegen-request-body-name: body
    post:
      tags:
      - user
      summary: Create user
      description: Creates an user
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        200:
          description: Successful operation
          content: {}
        400:
          description: User already created, invalid or missing fields or the message
            is not a json
          content: {}
      x-codegen-request-body-name: body
  /user/login:
    post:
      tags:
      - user
      summary: Login
      description: Logins a user
      requestBody:
        description: Login with a user
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
        required: true
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  login_token:
                    type: string
                  user:
                    $ref: '#/components/schemas/User'
        400:
          description: Missing fields or not a JSON
          content: {}
        403:
          description: Invalid credentials
          content: {}
        404:
          description: User not found
          content: {}
      x-codegen-request-body-name: body
  /user/recover_password:
    post:
      tags:
      - user
      summary: Recover password
      description: Sends an email to the user with the token required to recover the
        password
      requestBody:
        description: Sends an email to the user with the token required to recover
          the password
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
        required: true
      responses:
        200:
          description: Successful operation
          content: {}
        403:
          description: Not authorized
          content: {}
        404:
          description: User not found
          content: {}
      x-codegen-request-body-name: body
  /user/new_password:
    post:
      tags:
      - user
      summary: Set new password
      description: Sets a new password using a recovery token
      requestBody:
        description: Sets a new password using a recovery token
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                token:
                  type: string
                new_password:
                  type: string
        required: true
      responses:
        200:
          description: Successful operation
          content: {}
        400:
          description: Missing fields, body is not a json or recovery token invalid
          content: {}
        403:
          description: Not authorized
          content: {}
        404:
          description: User not found
          content: {}
      x-codegen-request-body-name: body
  /user/video:
    post:
      tags:
        - video
      summary: Upload a video
      description: Uploads a new video
      parameters:
        - name: email
          in: query
          description: The user name that uploaded the video
          required: true
          schema:
            type: string
      requestBody:
        description: Video data
        content:
          video/*:
            schema:
              type: string
              format: binary
          application/form:
            schema:
              $ref: '#/components/schemas/Video'
        required: true
      security:
        - bearerAuth: []
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  video:
                    $ref: '#/components/schemas/Video'
        400:
          description: Missing fields or invalid video format
          content: {}
        401:
          description: Access token is missing or invalid
          content: {}
        403:
          description: Not authorized
          content: {}
      x-codegen-request-body-name: body
  /user/videos:
    get:
      tags:
        - video
      summary: Get users videos
      description: Get users videos
      security:
        - bearerAuth: []
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  video:
                    $ref: '#/components/schemas/Video'
        400:
          description: Missing email
          content: {}
        401:
          description: Access token is missing or invalid
          content: {}
        403:
          description: Not authorized
          content: {}
      x-codegen-request-body-name: body
  /user/friend_request:
    post:
      tags:
      - friendship
      summary: Created a friend request
      description: Created a friend request
      requestBody:
        description: Other user data
        content:
          application/json:
            schema:
              type: object
              properties:
                other_user_email:
                  type: string
        required: true
      security:
        - bearerAuth: []
      responses:
        200:
          description: Successful operation
          content: {}
        400:
          description: Missing fields, users already friend or request is not a json
          content: {}
        401:
          description: Access token is missing or invalid
          content: {}
        404:
          description: Other user not found
          content: {}
      x-codegen-request-body-name: body
  /user/friend_request/accept:
    post:
      tags:
      - friendship
      summary: Accepts a friend request
      description: Accepts a friend request
      requestBody:
        description: Other user data
        content:
          application/json:
            schema:
              type: object
              properties:
                other_user_email:
                  type: string
        required: true
      security:
        - bearerAuth: []
      responses:
        200:
          description: Successful operation
          content: {}
        400:
          description: Missing fields or request is not a json
          content: {}
        401:
          description: Access token is missing or invalid
          content: {}
        404:
          description: Unexistent friend request
          content: {}
      x-codegen-request-body-name: body
  /user/friend_request/reject:
    post:
      tags:
      - friendship
      summary: Rejects a friend request
      description: Rejects a friend request
      requestBody:
        description: Other user data
        content:
          application/json:
            schema:
              type: object
              properties:
                other_user_email:
                  type: string
        required: true
      security:
        - bearerAuth: []
      responses:
        200:
          description: Successful operation
          content: {}
        400:
          description: Missing fields or request is not a json
          content: {}
        401:
          description: Access token is missing or invalid
          content: {}
        404:
          description: Unexistent friend request
          content: {}
      x-codegen-request-body-name: body
  /user/friend_requests:
    get:
      tags:
        - friendship
      summary: List users that have a friend request pending for you
      description: List users that have a friend request pending for you
      security:
        - bearerAuth: []
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  video:
                    $ref: '#/components/schemas/User'
        401:
          description: Access token is missing or invalid
          content: {}
      x-codegen-request-body-name: body
  /user/friends:
    get:
      tags:
        - friendship
      summary: List users that have a friend request pending for you
      description: List users that have a friend request pending for you
      parameters:
        - name: email
          in: query
          description: The user's friends to get
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  video:
                    $ref: '#/components/schemas/User'
        400:
          description: Missing email
          content: {}
        401:
          description: Access token is missing or invalid
          content: {}
        403:
          description: Not authorized
          content: {}
      x-codegen-request-body-name: body
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
        fullname:
          type: string
        password:
          type: string
        phone_number:
          type: string
        photo:
          type: string
        admin:
          type: boolean
      xml:
        name: User
    Video:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        visible:
          type: string
        location:
          type: string
      xml:
        name: Video
